import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/db/prisma/prisma";
import { getSession } from "@/lib/session/session";

const generateReportSchema = z.object({
  type: z.enum(["assessment", "roadmap"]),
  id: z.string().min(1),
});

export async function POST(request: Request) {
  try {
    const session = await getSession();
    if (!session?.user?.id) {
      return NextResponse.json({ success: false, error: { code: "UNAUTHORIZED", message: "Not authenticated" } }, { status: 401 });
    }

    const body = await request.json();
    const validated = generateReportSchema.parse(body);

    let reportData: Record<string, unknown> = {};

    if (validated.type === "assessment") {
      const result = await prisma.assessmentResult.findFirst({
        where: { id: validated.id, userId: session.user.id },
        include: { assessment: true, answers: true },
      });
      if (!result) {
        return NextResponse.json({ success: false, error: { code: "NOT_FOUND", message: "Assessment not found" } }, { status: 404 });
      }
      reportData = {
        type: "assessment",
        title: result.assessment.title,
        scores: result.scores,
        completedAt: result.completedAt,
        userId: session.user.id,
      };
    } else {
      const roadmap = await prisma.careerRoadmap.findFirst({
        where: { id: validated.id, userId: session.user.id },
        include: { career: true },
      });
      if (!roadmap) {
        return NextResponse.json({ success: false, error: { code: "NOT_FOUND", message: "Roadmap not found" } }, { status: 404 });
      }
      reportData = {
        type: "roadmap",
        career: roadmap.career?.title ?? "Unknown",
        goal: roadmap.goalPosition,
        years: roadmap.yearsToGoal,
        milestones: roadmap.milestones,
        generatedAt: roadmap.generatedAt,
      };
    }

    const html = `
<!DOCTYPE html>
<html><head><title>Career OS Report</title>
<style>body{font-family:sans-serif;padding:40px;color:#1a1a2e}h1{color:#6366f1}table{width:100%;border-collapse:collapse}td,th{border:1px solid #e5e7eb;padding:8px;text-align:left}th{background:#f3f4f6}</style>
</head><body>
<h1>Career OS — ${validated.type === "assessment" ? "Assessment Report" : "Career Roadmap"}</h1>
<p>Generated: ${new Date().toLocaleDateString()}</p>
<table>${Object.entries(reportData).map(([k, v]) => `<tr><th>${k}</th><td>${typeof v === "object" ? JSON.stringify(v) : String(v)}</td></tr>`).join("")}</table>
<p style="margin-top:40px;color:#6b7280;font-size:12px">This report is generated by Career OS (careeros.ai)</p>
</body></html>`;

    return new NextResponse(html, {
      headers: {
        "Content-Type": "text/html",
        "Content-Disposition": `attachment; filename="career-os-${validated.type}-report.html"`,
      },
    });
  } catch (error) {
    if (error instanceof z.ZodError) {
      return NextResponse.json({ success: false, error: { code: "VALIDATION_ERROR", message: "Invalid input" } }, { status: 400 });
    }
    return NextResponse.json({ success: false, error: { code: "INTERNAL_ERROR", message: "Something went wrong" } }, { status: 500 });
  }
}
