/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminDegreesRouteImport } from './routes/admin.degrees'
import { Route as AdminCollegesRouteImport } from './routes/admin.colleges'
import { Route as AdminCareersRouteImport } from './routes/admin.careers'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRoadmapRouteImport } from './routes/_app.roadmap'
import { Route as AppReportRouteImport } from './routes/_app.report'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppParentRouteImport } from './routes/_app.parent'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppAssessmentRouteImport } from './routes/_app.assessment'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDegreesRoute = AdminDegreesRouteImport.update({
  id: '/degrees',
  path: '/degrees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollegesRoute = AdminCollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCareersRoute = AdminCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoadmapRoute = AppRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AppRoute,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppParentRoute = AppParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentRoute = AppAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/assessment': typeof AppAssessmentRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/parent': typeof AppParentRoute
  '/profile': typeof AppProfileRoute
  '/report': typeof AppReportRoute
  '/roadmap': typeof AppRoadmapRoute
  '/settings': typeof AppSettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/colleges': typeof AdminCollegesRoute
  '/admin/degrees': typeof AdminDegreesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/share/$token': typeof ShareTokenRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/assessment': typeof AppAssessmentRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/parent': typeof AppParentRoute
  '/profile': typeof AppProfileRoute
  '/report': typeof AppReportRoute
  '/roadmap': typeof AppRoadmapRoute
  '/settings': typeof AppSettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/colleges': typeof AdminCollegesRoute
  '/admin/degrees': typeof AdminDegreesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/share/$token': typeof ShareTokenRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/_app/assessment': typeof AppAssessmentRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/parent': typeof AppParentRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/report': typeof AppReportRoute
  '/_app/roadmap': typeof AppRoadmapRoute
  '/_app/settings': typeof AppSettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/colleges': typeof AdminCollegesRoute
  '/admin/degrees': typeof AdminDegreesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/share/$token': typeof ShareTokenRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/language'
    | '/login'
    | '/pricing'
    | '/assessment'
    | '/billing'
    | '/dashboard'
    | '/parent'
    | '/profile'
    | '/report'
    | '/roadmap'
    | '/settings'
    | '/admin/analytics'
    | '/admin/careers'
    | '/admin/colleges'
    | '/admin/degrees'
    | '/admin/reports'
    | '/admin/users'
    | '/share/$token'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/language'
    | '/login'
    | '/pricing'
    | '/assessment'
    | '/billing'
    | '/dashboard'
    | '/parent'
    | '/profile'
    | '/report'
    | '/roadmap'
    | '/settings'
    | '/admin/analytics'
    | '/admin/careers'
    | '/admin/colleges'
    | '/admin/degrees'
    | '/admin/reports'
    | '/admin/users'
    | '/share/$token'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/language'
    | '/login'
    | '/pricing'
    | '/_app/assessment'
    | '/_app/billing'
    | '/_app/dashboard'
    | '/_app/parent'
    | '/_app/profile'
    | '/_app/report'
    | '/_app/roadmap'
    | '/_app/settings'
    | '/admin/analytics'
    | '/admin/careers'
    | '/admin/colleges'
    | '/admin/degrees'
    | '/admin/reports'
    | '/admin/users'
    | '/share/$token'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LanguageRoute: typeof LanguageRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/degrees': {
      id: '/admin/degrees'
      path: '/degrees'
      fullPath: '/admin/degrees'
      preLoaderRoute: typeof AdminDegreesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/colleges': {
      id: '/admin/colleges'
      path: '/colleges'
      fullPath: '/admin/colleges'
      preLoaderRoute: typeof AdminCollegesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/careers': {
      id: '/admin/careers'
      path: '/careers'
      fullPath: '/admin/careers'
      preLoaderRoute: typeof AdminCareersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roadmap': {
      id: '/_app/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AppRoadmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/report': {
      id: '/_app/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parent': {
      id: '/_app/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof AppParentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assessment': {
      id: '/_app/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AppAssessmentRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAssessmentRoute: typeof AppAssessmentRoute
  AppBillingRoute: typeof AppBillingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppParentRoute: typeof AppParentRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportRoute: typeof AppReportRoute
  AppRoadmapRoute: typeof AppRoadmapRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssessmentRoute: AppAssessmentRoute,
  AppBillingRoute: AppBillingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppParentRoute: AppParentRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportRoute: AppReportRoute,
  AppRoadmapRoute: AppRoadmapRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCareersRoute: typeof AdminCareersRoute
  AdminCollegesRoute: typeof AdminCollegesRoute
  AdminDegreesRoute: typeof AdminDegreesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCareersRoute: AdminCareersRoute,
  AdminCollegesRoute: AdminCollegesRoute,
  AdminDegreesRoute: AdminDegreesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LanguageRoute: LanguageRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
